"""
Backend Core Package

Core utilities for configuration, cryptography, validation, exceptions, and dependencies
"""

# Configuration
from backend.core.config import (
    settings,
    get_settings,
    is_production,
    is_development,
    is_testing,
    get_database_url,
    get_redis_url,
    get_cors_origins,
)

# Cryptography
from backend.core.crypto import (
    hash_password,
    verify_password,
    generate_api_key,
    hash_api_key,
    create_access_token,
    create_refresh_token,
    decode_token,
    generate_reset_token,
    generate_verification_code,
    hash_data,
    verify_token_type,
    constant_time_compare,
)

# Validators
from backend.core.validators import (
    validate_aws_account_id,
    validate_aws_role_arn,
    validate_aws_region,
    validate_instance_id,
    validate_vpc_id,
    validate_cluster_name,
    validate_timezone,
    validate_schedule_matrix,
    validate_percentage,
    validate_spot_percentage,
    validate_instance_type,
    validate_k8s_version,
    validate_ip_address,
    validate_cidr_block,
    validate_password_strength,
    validate_uuid,
)

# Exceptions
from backend.core.exceptions import (
    SpotOptimizerException,
    AuthenticationError,
    InvalidCredentialsError,
    TokenExpiredError,
    InvalidTokenError,
    AuthorizationError,
    InsufficientPermissionsError,
    ResourceNotFoundError,
    ResourceAlreadyExistsError,
    ResourceConflictError,
    ValidationError,
    InvalidInputError,
    AWSError,
    AWSAuthenticationError,
    AWSResourceNotFoundError,
    AWSAccessDeniedError,
    AWSRateLimitError,
    ClusterError,
    ClusterNotFoundError,
    ClusterNotActiveError,
    AgentNotInstalledError,
    AgentTimeoutError,
    DatabaseError,
    DatabaseConnectionError,
    DatabaseIntegrityError,
    OptimizationError,
    OptimizationJobNotFoundError,
    OptimizationJobFailedError,
    PolicyError,
    InvalidPolicyError,
    RateLimitError,
    ExternalServiceError,
    EmailServiceError,
    StripeError,
    FileError,
    FileTooLargeError,
    InvalidFileTypeError,
    MLModelError,
    MLModelNotFoundError,
    MLModelVersionConflictError,
    InvalidModelError,
)

# Dependencies
from backend.core.dependencies import (
    get_current_user_context,
    get_current_user,
    require_super_admin,
    verify_cluster_ownership,
    verify_template_ownership,
    verify_account_ownership,
    get_api_key_cluster,
    get_optional_user,
    get_database_session,
)

# Logging
from backend.core.logger import (
    setup_logging,
    get_logger,
    StructuredLogger,
    log_request,
    log_database_query,
    log_aws_api_call,
    log_optimization_job,
    log_audit_event,
)

__all__ = [
    # Configuration
    "settings",
    "get_settings",
    "is_production",
    "is_development",
    "is_testing",
    "get_database_url",
    "get_redis_url",
    "get_cors_origins",
    # Cryptography
    "hash_password",
    "verify_password",
    "generate_api_key",
    "hash_api_key",
    "create_access_token",
    "create_refresh_token",
    "decode_token",
    "generate_reset_token",
    "generate_verification_code",
    "hash_data",
    "verify_token_type",
    "constant_time_compare",
    # Validators
    "validate_aws_account_id",
    "validate_aws_role_arn",
    "validate_aws_region",
    "validate_instance_id",
    "validate_vpc_id",
    "validate_cluster_name",
    "validate_timezone",
    "validate_schedule_matrix",
    "validate_percentage",
    "validate_spot_percentage",
    "validate_instance_type",
    "validate_k8s_version",
    "validate_ip_address",
    "validate_cidr_block",
    "validate_password_strength",
    "validate_uuid",
    # Exceptions
    "SpotOptimizerException",
    "AuthenticationError",
    "InvalidCredentialsError",
    "TokenExpiredError",
    "InvalidTokenError",
    "AuthorizationError",
    "InsufficientPermissionsError",
    "ResourceNotFoundError",
    "ResourceAlreadyExistsError",
    "ResourceConflictError",
    "ValidationError",
    "InvalidInputError",
    "AWSError",
    "AWSAuthenticationError",
    "AWSResourceNotFoundError",
    "AWSAccessDeniedError",
    "AWSRateLimitError",
    "ClusterError",
    "ClusterNotFoundError",
    "ClusterNotActiveError",
    "AgentNotInstalledError",
    "AgentTimeoutError",
    "DatabaseError",
    "DatabaseConnectionError",
    "DatabaseIntegrityError",
    "OptimizationError",
    "OptimizationJobNotFoundError",
    "OptimizationJobFailedError",
    "PolicyError",
    "InvalidPolicyError",
    "RateLimitError",
    "ExternalServiceError",
    "EmailServiceError",
    "StripeError",
    "FileError",
    "FileTooLargeError",
    "InvalidFileTypeError",
    "MLModelError",
    "MLModelNotFoundError",
    "MLModelVersionConflictError",
    "InvalidModelError",
    # Dependencies
    "get_current_user_context",
    "get_current_user",
    "require_super_admin",
    "verify_cluster_ownership",
    "verify_template_ownership",
    "verify_account_ownership",
    "get_api_key_cluster",
    "get_optional_user",
    "get_database_session",
    # Logging
    "setup_logging",
    "get_logger",
    "StructuredLogger",
    "log_request",
    "log_database_query",
    "log_aws_api_call",
    "log_optimization_job",
    "log_audit_event",
]
