"""add_transfer_analysis_model

Revision ID: 10b272181247
Revises: 6a2013a1b9b8
Create Date: 2026-01-19 06:57:13.096013+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10b272181247'
down_revision = '6a2013a1b9b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_transfer_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('transfer_type', sa.String(length=100), nullable=False),
    sa.Column('total_bytes_gb', sa.Float(), nullable=True),
    sa.Column('monthly_cost', sa.Float(), nullable=True),
    sa.Column('source_resource_id', sa.String(length=100), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=True),
    sa.Column('estimated_savings', sa.Float(), nullable=True),
    sa.Column('recommendation_detail', sa.JSON(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_transfer_analysis_account_id'), 'data_transfer_analysis', ['account_id'], unique=False)
    op.create_index(op.f('ix_data_transfer_analysis_id'), 'data_transfer_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_data_transfer_analysis_organization_id'), 'data_transfer_analysis', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_transfer_analysis_organization_id'), table_name='data_transfer_analysis')
    op.drop_index(op.f('ix_data_transfer_analysis_id'), table_name='data_transfer_analysis')
    op.drop_index(op.f('ix_data_transfer_analysis_account_id'), table_name='data_transfer_analysis')
    op.drop_table('data_transfer_analysis')
    # ### end Alembic commands ###
