"""add_rds_analysis_model

Revision ID: 6a2013a1b9b8
Revises: 9cccf2d13105
Create Date: 2026-01-19 06:53:00.354123+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6a2013a1b9b8'
down_revision = '9cccf2d13105'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rds_instance_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('db_instance_identifier', sa.String(length=100), nullable=False),
    sa.Column('engine', sa.String(length=50), nullable=False),
    sa.Column('instance_class', sa.String(length=50), nullable=False),
    sa.Column('multi_az', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('environment_tag', sa.String(length=50), nullable=True),
    sa.Column('is_production', sa.Boolean(), nullable=True),
    sa.Column('avg_cpu_utilization', sa.Float(), nullable=True),
    sa.Column('max_cpu_utilization', sa.Float(), nullable=True),
    sa.Column('avg_db_connections', sa.Float(), nullable=True),
    sa.Column('current_monthly_cost', sa.Float(), nullable=True),
    sa.Column('estimated_savings', sa.Float(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=True),
    sa.Column('recommendation_impact', sa.String(length=20), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rds_instance_analysis_account_id'), 'rds_instance_analysis', ['account_id'], unique=False)
    op.create_index(op.f('ix_rds_instance_analysis_db_instance_identifier'), 'rds_instance_analysis', ['db_instance_identifier'], unique=False)
    op.create_index(op.f('ix_rds_instance_analysis_id'), 'rds_instance_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_rds_instance_analysis_organization_id'), 'rds_instance_analysis', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rds_instance_analysis_organization_id'), table_name='rds_instance_analysis')
    op.drop_index(op.f('ix_rds_instance_analysis_id'), table_name='rds_instance_analysis')
    op.drop_index(op.f('ix_rds_instance_analysis_db_instance_identifier'), table_name='rds_instance_analysis')
    op.drop_index(op.f('ix_rds_instance_analysis_account_id'), table_name='rds_instance_analysis')
    op.drop_table('rds_instance_analysis')
    # ### end Alembic commands ###
