"""add_ri_utilization_model

Revision ID: 58ae9f1e2d82
Revises: 5f5416e8114a
Create Date: 2026-01-19 06:44:22.845379+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58ae9f1e2d82'
down_revision = '5f5416e8114a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ri_utilization',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('reservation_id', sa.String(length=100), nullable=False),
    sa.Column('instance_type', sa.String(length=50), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('availability_zone', sa.String(length=50), nullable=True),
    sa.Column('offering_class', sa.String(length=20), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('instance_count', sa.Integer(), nullable=True),
    sa.Column('upfront_cost', sa.Float(), nullable=True),
    sa.Column('hourly_cost', sa.Float(), nullable=True),
    sa.Column('monthly_cost', sa.Float(), nullable=True),
    sa.Column('utilization_percentage', sa.Float(), nullable=True),
    sa.Column('utilized_hours', sa.Float(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('monthly_waste', sa.Float(), nullable=True),
    sa.Column('annual_waste', sa.Float(), nullable=True),
    sa.Column('unused_days', sa.Integer(), nullable=True),
    sa.Column('estimated_resale_value', sa.Float(), nullable=True),
    sa.Column('resale_percentage', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('days_remaining', sa.Integer(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('analysis_period_days', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=True),
    sa.Column('recommendation_detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ri_utilization_account_id'), 'ri_utilization', ['account_id'], unique=False)
    op.create_index(op.f('ix_ri_utilization_id'), 'ri_utilization', ['id'], unique=False)
    op.create_index(op.f('ix_ri_utilization_organization_id'), 'ri_utilization', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ri_utilization_reservation_id'), 'ri_utilization', ['reservation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ri_utilization_reservation_id'), table_name='ri_utilization')
    op.drop_index(op.f('ix_ri_utilization_organization_id'), table_name='ri_utilization')
    op.drop_index(op.f('ix_ri_utilization_id'), table_name='ri_utilization')
    op.drop_index(op.f('ix_ri_utilization_account_id'), table_name='ri_utilization')
    op.drop_table('ri_utilization')
    # ### end Alembic commands ###
