"""add_s3_analysis_model

Revision ID: 9cccf2d13105
Revises: 58ae9f1e2d82
Create Date: 2026-01-19 06:48:14.454137+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cccf2d13105'
down_revision = '58ae9f1e2d82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3_bucket_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('bucket_name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('total_size_bytes', sa.Float(), nullable=True),
    sa.Column('object_count', sa.Integer(), nullable=True),
    sa.Column('size_standard', sa.Float(), nullable=True),
    sa.Column('size_ia', sa.Float(), nullable=True),
    sa.Column('size_glacier', sa.Float(), nullable=True),
    sa.Column('size_deep_archive', sa.Float(), nullable=True),
    sa.Column('size_intelligent', sa.Float(), nullable=True),
    sa.Column('monthly_cost', sa.Float(), nullable=True),
    sa.Column('estimated_savings', sa.Float(), nullable=True),
    sa.Column('has_lifecycle_policy', sa.Boolean(), nullable=True),
    sa.Column('is_versioning_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_accessed_date', sa.DateTime(), nullable=True),
    sa.Column('size_hot', sa.Float(), nullable=True),
    sa.Column('size_warm', sa.Float(), nullable=True),
    sa.Column('size_cold', sa.Float(), nullable=True),
    sa.Column('size_frozen', sa.Float(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=True),
    sa.Column('recommendation_detail', sa.JSON(), nullable=True),
    sa.Column('last_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s3_bucket_analysis_account_id'), 's3_bucket_analysis', ['account_id'], unique=False)
    op.create_index(op.f('ix_s3_bucket_analysis_bucket_name'), 's3_bucket_analysis', ['bucket_name'], unique=False)
    op.create_index(op.f('ix_s3_bucket_analysis_id'), 's3_bucket_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_s3_bucket_analysis_organization_id'), 's3_bucket_analysis', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_s3_bucket_analysis_organization_id'), table_name='s3_bucket_analysis')
    op.drop_index(op.f('ix_s3_bucket_analysis_id'), table_name='s3_bucket_analysis')
    op.drop_index(op.f('ix_s3_bucket_analysis_bucket_name'), table_name='s3_bucket_analysis')
    op.drop_index(op.f('ix_s3_bucket_analysis_account_id'), table_name='s3_bucket_analysis')
    op.drop_table('s3_bucket_analysis')
    # ### end Alembic commands ###
