apiVersion: v1
kind: Secret
metadata:
  name: spot-agent-config
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  API_KEY: {{ .Values.config.apiKey | quote }}
  BACKEND_URL: {{ .Values.config.backendUrl | quote }}
  CLUSTER_ID: {{ .Values.config.clusterId | quote }}
