"""add launched_by to instances

Revision ID: ed7f8dd2b28e
Revises: 421d795851e5
Create Date: 2026-03-14 05:23:22.164621+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7f8dd2b28e'
down_revision = '421d795851e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances', sa.Column('launched_by', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_instances_launched_by'), 'instances', ['launched_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instances_launched_by'), table_name='instances')
    op.drop_column('instances', 'launched_by')
    # ### end Alembic commands ###
