"""KarpenterEvent model — persists K8s events reported by the event-watcher sidecar.

Events are generated by the karpenter_watcher.py sidecar running inside the agent
DaemonSet pod.  The watcher streams the K8s event API, filters for events whose
source is ``karpenter`` (or namespace karpenter-system), and POSTs them to the
backend.  This gives the ML rebalancer visibility into Karpenter acting
independently (e.g. provisioning t4g.micro to satisfy pending pods or consolidating
underutilised nodes).
"""
from sqlalchemy import Column, Integer, String, DateTime, Boolean, Text, ForeignKey, Index, func
from sqlalchemy.dialects.postgresql import JSONB
from backend.models.base import Base


class KarpenterEvent(Base):
    """One K8s event emitted by Karpenter, as reported by the agent sidecar."""

    __tablename__ = 'karpenter_events'
    __table_args__ = (
        Index('ix_karpenter_events_cluster_id', 'cluster_id'),
        Index('ix_karpenter_events_event_reason', 'event_reason'),
        Index('ix_karpenter_events_received_at', 'received_at'),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    cluster_id = Column(
        String(100),
        ForeignKey('clusters.id', ondelete='CASCADE'),
        nullable=False,
    )

    # K8s event.reason — e.g. "NodeClaimCreated", "NodeClaimDeleted", "Consolidated",
    # "DisruptionBlocked", "WaitingOnReadiness"
    event_reason = Column(String(100), nullable=False)

    # K8s event.source.component — usually "karpenter"
    event_source = Column(String(100), nullable=True)

    # K8s involvedObject.kind and .name (e.g. "NodeClaim", "default-abc12")
    involved_object_kind = Column(String(100), nullable=True)
    involved_object_name = Column(String(255), nullable=True)

    # Human-readable message from the K8s event
    message = Column(Text, nullable=True)

    # Full event payload as posted by the agent sidecar
    event_payload = Column(JSONB, nullable=True)

    # Timestamp of the original K8s event (firstTimestamp / eventTime)
    event_time = Column(DateTime, nullable=True)

    # When this row was written to the DB
    received_at = Column(DateTime, server_default=func.now(), nullable=False)

    # True if the rebalancer was paused as a result of this event
    triggered_pause = Column(Boolean, server_default='false', nullable=False)

    def __repr__(self):
        return (
            f"<KarpenterEvent(id={self.id}, cluster={self.cluster_id}, "
            f"reason={self.event_reason}, obj={self.involved_object_name})>"
        )
