"""
OptimizerProposal model — stores pool switch and right-sizing proposals
generated by the optimizer coordinator.
"""
from sqlalchemy import Column, String, Float, DateTime, Enum
from backend.models.base import Base
from uuid import uuid4
from datetime import datetime
import enum


class ProposalStatus(enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXECUTED = "EXECUTED"


class OptimizerProposal(Base):
    __tablename__ = 'optimizer_proposals'

    id = Column(String(36), primary_key=True, default=lambda: str(uuid4()))
    cluster_id = Column(String(36), nullable=False, index=True)
    node_name = Column(String(255))
    current_instance_type = Column(String(50))
    proposed_instance_type = Column(String(50))
    proposed_az = Column(String(50))
    estimated_savings = Column(Float)
    risk_delta = Column(Float)
    status = Column(Enum(ProposalStatus), default=ProposalStatus.PENDING)
    created_at = Column(DateTime, default=datetime.utcnow)
    executed_at = Column(DateTime, nullable=True)
