AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates a cross-account IAM Role for the Spot Optimization Platform.'

Parameters:
  ExternalId:
    Type: String
    Description: 'Unique Security Token provided by the dashboard'
  PlatformPrincipal:
    Type: String
    Description: 'The AWS Account ID of the Optimization Platform'

Resources:
  OptimizationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'SpotOptimizer-Role-${ExternalId}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Ref PlatformPrincipal
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/SecurityAudit'
        - 'arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess'

Outputs:
  RoleArn:
    Description: 'The ARN of the created role to paste in the dashboard'
    Value: !GetAtt OptimizationRole.Arn
